- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: f82fb149af2c1b552b50e3e38e38ed3a44d4cda1
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: double-quote-string-fixer
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
    - id: flake8
