language: python
dist: trusty
python: 3.6
sudo: required
before_install:
 - sudo add-apt-repository -y ppa:deadsnakes/ppa
 - sudo add-apt-repository -y ppa:pypy/ppa
 - sudo apt-get -qq update
 - sudo apt-get -y install python2.6 python3.3 python3.5 pypy

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
  - TOX_ENV=pypy
  - TOX_ENV=py2_jieba
  - TOX_ENV=py3_jieba
  - TOX_ENV=py3_env

install:
  - pip install coveralls codecov
  - pip install tox
  - pip install -r requirements_dev.txt

script:
  - pre-commit run --all-files
  - tox -e $TOX_ENV
  - python setup.py install
  - pypinyin hello
  - echo hello | pypinyin
  - pypinyin < setup.cfg

after_script:
  - codecov
  - coveralls
