language: python
python:
  - 3.5

sudo: false

env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=pypy
  - TOX_ENV=py2_snownlp
  - TOX_ENV=py2_jieba
  - TOX_ENV=py3_jieba
  - TOX_ENV=py3_env

install:
  - pip install coveralls
  - pip install tox
  - pip install -r requirements_dev.txt

script:
  - pre-commit run --all-files
  - tox -e $TOX_ENV
  - python setup.py install
  - pypinyin hello
  - echo hello | pypinyin
  - pypinyin < setup.cfg

after_script:
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: always
