language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"
  - "3.4"

install:
  - "pip install coveralls"
  - "pip install pytest-cov"
  - "pip install pytest-random"
  - "pip install -e ."

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements_dev.txt; fi
  - "python setup.py test"
  - "python setup.py develop"
  - "py.test --cov pypinyin tests/"

after_script:
  - "coveralls"

notifications:
  email:
    on_success: change
    on_failure: always
