language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install coveralls"
  - "pip install pytest-cov"
  - "pip install pytest-random"

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install -r requirements_dev.txt; fi
  - "python setup.py install"
  - "py.test --cov pypinyin tests/"

after_script:
  - "coveralls"

matrix:
  allow_failures:
    - python: "3.2"

notifications:
  email:
    on_success: change
    on_failure: always
